### ISSUE TITLE
Examine gopher license

### ISSUE THREAD

**Issue by mono0926** [mono0926/gopher-line-stamp#1]

**Comment by mono0926** [comment]
@abe-perorist

レポジトリ作りました(　´･‿･｀)

**Comment by mono0926** [comment]
[LINE - クリエイターズスタンプ](https://store.line.me/stickershop/showcase/top_creators/ja)の検索だとヒットしないけど、くまもんスタンプとかある。
[ゆるキャラのLINEクリエイターズスタンプ - NAVER まとめ](http://matome.naver.jp/odai/2140825200441244301)

例えば、[くまモンのスタンプ(日常会話） - LINE クリエイターズスタンプ](https://store.line.me/stickershop/product/1027361/ja)のように`©2010 kumamoto pref. kumamon#14859`で著作権表示してたり。

**Comment by mono0926** [comment]
だめかも(´・︵・｀)

> 二次創作を許容している著作権者の作品に関する二次創作スタンプも同様に認められないとの回答を得られた。

[自作でも二次創作LINEスタンプは販売禁止──LINEクリエイターズマーケットには著作権に関するガイドラインなし | アプリオ](http://appllio.com/20140226-4912-line-creators-market-nijisousaku-stamp)

**Comment by mono0926** [comment]
Goに聞いたら良さそう

> Edd Robinson [8:19 PM] 
> mono: I think the plain CC attribution licence allows commercial use
> 
> Edd Robinson [8:20 PM]
> I think the `nc` version of the licence prohibits commercial use. I'm not a lawyer though :stuck_out_tongue:

**Comment by mono0926** [comment]
「ライセンス証明書」あればいけるっぽい。
さっきのは古い情報かな。

http://golang.org/doc/gopher/README を付けつつ、表記すればOKかなあ？

[LINEスタンプを作って販売してみた！やってみて分かった押さえるべき12のポイント【追記あり】](http://gaiax-socialmedialab.jp/line/321)

**Comment by mono0926** [comment]
[Problem Report Form│LINE](https://contact.line.me/) に問い合わせ中。

[【LINE】クリエイターズマーケット審査ガイドラインに関する問い合わせ先 | LINEの仕組み](http://did2memo.net/2014/07/09/naver-line-creators-market-customer-service/)

**Comment by mono0926** [comment]
自分が著作権を持っていることを主張する必要がある模様なので方針展開: #4

> LINE Creators Marketでは、著作権を持っていないスタンプの販売は行えません。
> 著作権を証明していただくためには、ライセンス証明書/契約書など必要な書類を添付していただく必要がございます。

**Comment by abe-perorist** [comment]
これは、つらたん

**Comment by mono0926** [comment]
つらすぎて多分2・3日仕事が手に付かないです(　´･‿･｀)
